server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    consul:
      host: ${SPRING_CLOUD_CONSUL_HOST}
      port: ${SPRING_CLOUD_CONSUL_PORT}
      discovery:
        enabled: true
        prefer-ip-address: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            maxAge: 3600

      routes:
        - id: trip-service-route
          uri: lb://trip-service
          predicates:
            - Path=/trip-service/**
          filters:
            - StripPrefix=1
            - name: RequestLogging
            - name: Authentication

        - id: suggestion-service-route
          uri: lb://suggestion-service
          predicates:
            - Path=/suggestion-service/**
          filters:
            - StripPrefix=1
            - name: Authentication

        - id: auth-service-route
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1
            - name: Authentication

  # Configuração do Springdoc para descoberta automática no Gateway
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
    swagger-ui:
      enabled: true
      path: /swagger-ui.html
      swagger-ui-config-url: /v3/api-docs/swagger-config
  swagger-ui:
    use-root-path: true
    urls:
      - name: Trip Service
        url: /trip-service/v3/api-docs
      - name: Suggestion Service
        url: /suggestion-service/v3/api-docs
      - name: Auth Service
        url: /auth-service/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

jwt:
  secret: ${JWT_SECRET_KEY:92B4E9A7C3F8D6E1A0B5C4F3E2D1A9B8C7D6E5F4A3B2C1D0E9F8A7B6C5D4E3F2}

public-endpoints:
  - /auth-service/api/v1/users/register
  - /auth-service/api/v1/users/login
  - /auth-service/v3/api-docs
  - /trip-service/v3/api-docs
  - /suggestion-service/v3/api-docs
  - /v3/api-docs
  - /swagger-ui.html
  - /v3/api-docs/swagger-config

logging:
  level:
    org.springframework.cloud.gateway: INFO
    com.fernandodev.apigateway: INFO
