server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            maxAge: 3600

      routes:
        - id: trip-service-route
          uri: ${TRIP_SERVICE_URL}
          predicates:
            - Path=/api/v1/trips/**
          filters:
            - name: RequestLogging

        - id: suggestion-service-route
          uri: ${SUGGESTION_SERVICE_URL}
          predicates:
            - Path=/api/v1/suggestions/**

        - id: user-service-route
          uri: ${AUTH_SERVICE_URL}
          predicates:
            - Path=/api/v1/users/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.fernandodev.apigateway: INFO
