spring:
  cloud:
    gateway:
      routes:
        - id: trip-service-route
          uri: http://localhost:8000
          predicates:
            - Path=/trip-service/**
          filters:
            - StripPrefix=1

        - id: suggestion-service-route
          uri: http://localhost:8010
          predicates:
            - Path=/suggestion-service/**
          filters:
            - StripPrefix=1

        - id: auth-service-route
          uri: http://localhost:8020
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1

springdoc:
  api-docs:
    path: /api-docs

jwt:
  secret: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351

public-endpoints:
  - /auth-service/api/v1/users/register
  - /auth-service/api/v1/users/login
