server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            maxAge: 3600

      routes:
        - id: trip-service-route
          uri: ${TRIP_SERVICE_URL}
          predicates:
            - Path=/trip-service/**
          filters:
            - StripPrefix=1
            - name: RequestLogging
            - name: Authentication

        - id: suggestion-service-route
          uri: ${SUGGESTION_SERVICE_URL}
          predicates:
            - Path=/suggestion-service/**
          filters:
            - StripPrefix=1
            - name: Authentication

        - id: auth-service-route
          uri: ${AUTH_SERVICE_URL}
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1
            - name: Authentication

  # Configuração do Springdoc para o Gateway
  springdoc:
    swagger-ui:
      urls:
        - name: "Trip Service"
          url: "/trip-service/v3/api-docs"
        - name: "Suggestion Service"
          url: "/suggestion-service/v3/api-docs"
        - name: "Auth Service"
          url: "/auth-service/v3/api-docs"

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

jwt:
  secret: ${JWT_SECRET_KEY:92B4E9A7C3F8D6E1A0B5C4F3E2D1A9B8C7D6E5F4A3B2C1D0E9F8A7B6C5D4E3F2} # TODO: Mover para variável de ambiente

public-endpoints:
  - /api/v1/users/register
  - /api/v1/users/login

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.fernandodev.apigateway: INFO
